from typing import Annotated, Any, Dict, List

from langchain_core.messages import AnyMessage
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict


class MultiAgentDataState(TypedDict):
    # Standard conversation history
    messages: Annotated[List[AnyMessage], add_messages]

    # Internal variables passed between specific agents
    plan_steps: List[str]  # The breakdown generated by the Planner
    pdf_context: str  # Information extracted from the PDF
    sql_query: str  # The current query generated by the SQL Agent
    sql_result: List[Dict[str, Any]]  # The raw data returned by the DB
    sql_error: str  # Any error message thrown by the DB execution
    final_chart_path: str  # Path to the generated Matplotlib chart image
